name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@v0.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
